### ISSUE TITLE
Enable splitting by absolute time rather than relative duration

### ISSUE THREAD

**Issue by clange** [justintaft/org-clock-split#5]
Great work! Actually quite similar to something I have implemented before. However, [my code](https://github.com/clange/emacs/blob/master/.emacs.d/init/org-clock.el#L35) does not split by relative duration ("split after 1 hour"), but by absolute point in time ("split at 18:30"). As my code is under the permissive ISC license, feel free to include it into your package.

**Comment by miguelmorin** [comment]
I coded a branch that splits by absolute time, such as `9.20`, and allows to split from the end of a time segment.

https://github.com/miguelmorin/org-clock-split/blob/add-splitting-from-end/org-clock-split.el

Shall I make a PR?

**Comment by oneupsecurity** [comment]
@miguelmorin Yes please! I'm a bit busy with work today but can review over the weekend.

**Comment by miguelmorin** [comment]
I started on the PR and realized that some changes need discussion compared to [this branch in my fork](https://github.com/miguelmorin/org-clock-split/tree/add-splitting-from-end). I added an optional argument `from-end` that defaults to `nil` for backwards compatibility, but I think optional arguments are incompatible with user prompts in Emacs. My local solution was to define two wrapper functions that take user prompts. To keep backwards compatibility for splitting from the end, I think that the code inside `org-clock-split` would need to be duplicated into another function `org-clock-split-from-end` for example.

**Comment by oneupsecurity** [comment]
> To keep backwards compatibility for splitting from the end, I think that the code inside `org-clock-split` would need to be duplicated into another function `org-clock-split-from-end` for example.

Having two functions is fine for now.  Instead of copying and pasting code between functions, maybe we can refactor  the code for maximum reuse. Ex, `org-clock-split-split-line-into-timestamps` can take an additional argument to specify how to split the time.

**Comment by miguelmorin** [comment]
Sorry for the delay, I was overwhelmed for a while. I now know how to write functions that take a prefix argument and a minibuffer argument (from [this thread](https://stackoverflow.com/questions/59514506/elisp-interactive-function-with-both-prefix-argument-and-user-input-as-optional)) so the code will be DRY. Which of these options would you prefer to split time from the end?

- `C-u org-clock-split RET 15m`
- `org-clock-split RET -15m`

Or shall I code both?

**Comment by justintaft** [comment]
@miguelmorin no worries, quite busy myself.  `C-u org-clock-split RET 15m` should be fine. thanks for checking :)

**Comment by miguelmorin** [comment]
I coded both, as I liked the ability to decide whether to split from start or end after deciding to split. Once you approve this PR, I'll add the code for merging clock entries for #9.
